### ISSUE TITLE
Typo in the Step 3

### ISSUE THREAD

**Issue by przybylzlasu** [storyofams/next-password-protect#24]
Hey,

in the code example for Step 3 you use the following line:

```
loginApiPath: "/login",
```

instead of

```
loginApiUrl: "/login",
```

**Comment by przybylzlasu** [comment]
Also the `cookieName` gets highlighted as non existent in the `interface PasswordProtectHOCOptions` but in the docs it is specified that you can add it as an option (or I didn't understand correctly :D)

**Comment by BJvdA** [comment]
Thanks for reporting! I've fixed the typo, also `cookieName` on `PasswordProtectHOC` was an old prop and is not used anymore.

**Comment by alejandrosobko** [comment]
@BJvdA and what about `cookieMaxAge`? it's also in the docs but not in the interface
