### ISSUE TITLE
Page rendering nothing

### ISSUE THREAD

**Issue by utkarshdubey** [storyofams/next-password-protect#39]
**Describe the bug**
After following the steps specified in the README, the Page should be displaying a password portal, however, it displays nothing at all.

**To Reproduce**

```jsx
export default function Post({ code, frontmatter }) {
  return frontmatter.protected ? (
    withPasswordProtect(
      <UnprotectedPost code={code} frontmatter={frontmatter} />,
      { loginApiUrl: "/login", checkApiUrl: "/checkPassword" }
    )
  ) : (
    <UnprotectedPost code={code} frontmatter={frontmatter} />
  );
}
```

This is what my page looks like. I'm conditionally checking if the frontmatter of a .md file contains the ``protected`` value and then rendering the component based on the boolean value.

**Expected behavior**
It should've rendered the password page or displayed an error however the page renders nothing. Other posts that do not have the ``protected`` value are rendering fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/29272078/150104995-ce326666-ec4a-44f6-ae0d-377d15541210.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 
**Additional context**
Not sure what the problem might be here, but the console does show this particular warning.
![image](https://user-images.githubusercontent.com/29272078/150105151-4d1268af-ac9a-421b-b5fe-a76b994e360a.png)

**Comment by BJvdA** [comment]
Hi @utkarshdubey,
The way this library works is that `withPasswordProtect` expects to be wrapped around the default export of `App` in `pages/_app.tsx`, it currently does not work by wrapping it around a single page.
Perhaps you can take a look at the source code and adjust it to fit your needs. Hope that helps
