### ISSUE TITLE
Subdomain support for next-password-cookie

### ISSUE THREAD

**Issue by korac** [storyofams/next-password-protect#41]
First of all, thanks for this package! It's really a handy one.

**Describe the problem**
I'm working on an app that supports custom subdomains.
Once logged in (with next-pass), I still need to repeat the same login process when navigating to each of the subdomains.

This happens due to the way the cookie is being set - `domain` attribute is omitted and thus it [defaults to the current host (excluding subdomains)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#:~:text=Age%20has%20precedence.-,Domain%3D%3Cdomain%2Dvalue%3E,specifications%2C%20leading%20dots%20in%20domain%20names%20(.example.com)%20are%20ignored.,-Multiple%20host/domain).

**Describe the solution**
I would like to have an option to opt out of the default behavior and set the domain explicitly to [allow subdomain support](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#:~:text=but%20if%20a%20domain%20is%20specified%2C%20then%20subdomains%20are%20always%20included.).

**Additional**
I'd be happy to offer help on this.

**Comment by BJvdA** [comment]
Hi @korac, thanks for the issue! Seems like a useful thing to support.
I think it should be possible to pass the `domain` to the cookie [here](https://github.com/storyofams/next-password-protect/blob/ae94db6d9d030be4fdd8a2ddd93d5cf284a627f2/src/api/loginHandler.ts#L42). Would you be open to making a PR with this?

**Comment by korac** [comment]
@BJvdA Thanks for the info! Will open a PR.
