### ISSUE TITLE
"Back to main website" bug

### ISSUE THREAD

**Issue by bikkimahato** [storyofams/next-password-protect#53]
Clicking on "Back to main website" makes it go to the GitHub page.

![image](https://user-images.githubusercontent.com/42492682/164044164-b36a739b-b75f-44f8-8d2b-54879c202467.png)

**Comment by BJvdA** [comment]
Hi, this is intended and can be configure using `backUrl`, like here: https://github.com/storyofams/next-password-protect/blob/master/example/src/pages/_app.tsx#L33
